#!/bin/bash

# install packets
pamac update --no-confirm
pamac install --no-confirm firefox playerctl mpv youtube-dl xorg-xev fish alacritty rofi nemo thunderbird
pamac build --no-confirm barriers barrier
install_pulse

# configs
# i3
cp ~/.scripts/i3_config_manjaro ~/.i3/config
# git
git config --global user.email "6976764+sqanch@users.noreply.github.com"
git config --global user.name "m3xit"
git config --global credential.helper cache
git config pull.rebase false
# shell
echo "" >> ~/.bashrc
echo "export EDITOR=vim" >> ~/.bashrc
echo "" >> ~/.bashrc
echo "exec fish" >> ~/.bashrc
# keyring
echo "auth       optional     pam_gnome_keyring.so" | sudo tee -a /etc/pam.d/login > /dev/null
echo "session    optional     pam_gnome_keyring.so auto_start" | sudo tee -a /etc/pam.d/login > /dev/null
# ufw
sudo systemctl enable ufw
sudo ufw enable
sudo ufw allow from 192.168.178.200
sudo ufw allow from 192.168.178.201
sudo ufw allow from 192.168.178.202
sudo ufw allow from 192.168.178.210
sudo ufw allow from 192.168.178.211
sudo ufw allow from 192.168.178.212
# ssd ftrim
sudo systemctl enable --now fstrim.timer
