#!/bin/bash
url=$1
time=$2
#mpv --ytdl-format="bestvideo[height<=?1080]+bestaudio/best" $url > /dev/null 2>&1 &
#exec mpv --ytdl-format="bestvideo[height<=?480]+bestaudio/best" $url > /dev/null 2>&1 &
i3-msg "exec mpv --ytdl-format='bestvideo[height<=?480]+bestaudio/best' $url" && sleep 1 && i3-msg "floating enable; resize set 480 270"
#mpv --ytdl-format="bestvideo[height<=?1080]+bestaudio/best" $url $time &
