#!/bin/bash
url=$1
time=$2
i3-msg "workspace --no-auto-back-and-forth 9"
#mpv --ytdl-format="bestvideo[height<=?1080]+bestaudio/best" $url > /dev/null 2>&1 &
mpv --ytdl-format="bestvideo[height<=?480]+bestaudio/best" $url > /dev/null 2>&1 &
#mpv --ytdl-format="bestvideo[height<=?1080]+bestaudio/best" $url $time &
