#!/bin/bash

/usr/lib/polkit-gnome/polkit-gnome-authentication-agent-1 &
nitrogen --restore
nm-applet &
pamac-tray &
# xautolock -time 10 -locker blurlock
~/.scripts/barrier max-xps13
#/usr/lib/kdeconnectd &
picom --config .config/picom/picom.conf -b --experimental-backends &
nextcloud &
libinput-gestures-setup start
xinput set-prop 11 "libinput Accel Speed" +0.1
/home/max/.i3/i3-battery-popup/i3-battery-popup -n -D -L 20 -l 10
