#!/bin/bash

/usr/lib/polkit-gnome/polkit-gnome-authentication-agent-1 &
nitrogen --restore
nm-applet &
pamac-tray &
# xautolock -time 10 -locker blurlock
~/.scripts/barrier max-vm-manjaro
/usr/lib/kdeconnectd &
